# Algèbre linéaire avec Numpy

In [5]:
import numpy as np

In [6]:
arr = np.arange(15).reshape((3, 5))
arr


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## La transposée

In [7]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

## Le produit matriciel

In [8]:
np.matmul(arr.T, arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [9]:
arr.T@arr

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

## Le produit scalaire

In [10]:
x = np.array([1,2,3,4,7])

In [11]:
y = np.array([5,8,9,7,9])

In [12]:
np.dot(x,y)

139

In [13]:
x.dot(y)

139

## Inverse

In [14]:
from numpy.linalg import inv

In [15]:
mat = np.array([[5,8,6,4], [7,8,2,1], [8,2,6,3], [1,4,9,6]])

In [16]:
mat

array([[5, 8, 6, 4],
       [7, 8, 2, 1],
       [8, 2, 6, 3],
       [1, 4, 9, 6]])

In [17]:
inv(mat)

array([[ 0.84615385, -0.61538462,  0.20512821, -0.56410256],
       [-0.5       ,  0.5       , -0.16666667,  0.33333333],
       [-4.23076923,  3.07692308, -0.35897436,  2.48717949],
       [ 6.53846154, -4.84615385,  0.61538462, -3.69230769]])